package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib 18.13
    - opencv 2.4.9*
    - cypico 0.2*
    - cyffld2 0.1.*
    - menpo 0.4.0|>=0.4.1,<0.5.0  # Make sure we ignore the alpha

test:

  requires:
    - nose

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv
    - menpodetect.pico
    - menpodetect.ffld2

  commands:
    - python -c "import nose; nose.main()" -s menpodetect

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
