package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib 18.13
    - opencv 2.4.9*
    - cypico 0.2*
    - menpo # 0.5.0 on release

test:

  requires:
    - nose

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv
    - menpodetect.pico

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
