package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy 1.9*
    - dlib 18.10
    - opencv 2.4.9*
    - cypico 0.2*
    - menpo 0.4.0a3

test:

  requires:
    - nose

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv
    - menpodetect.pico

  commands:
    - python -c "import nose; nose.main()" -s menpodetect

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
