package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib 18.*
    - opencv3 3.1.*
    - cypico 0.2.*
    - cyffld2 0.2.*
    - menpo 0.8.*

test:
  requires:
    - nose
    - mock
    - coverage

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv
    - menpodetect.pico
    - menpodetect.ffld2

  commands:
    - nosetests menpodetect -v --with-coverage --cover-package=menpodetect

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
