package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib 18.*
    - opencv 2.4.*  # [not py3k]
    - opencv3 3.1.* # [py3k]
    - cypico 0.2.*
    - cyffld2 0.2.*
    - menpo 0.6.*

test:
  requires:
    - nose
    - mock

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv
    - menpodetect.pico
    - menpodetect.ffld2

  commands:
    - nosetests menpodetect -v

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
