package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy 1.9.0
    - dlib 18.10
    - opencv 2.4.9.1
    - menpo

test:

  requires:
    - nose

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv

  commands:
    - python -c "import nose; nose.main()" -s menpodetect

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
