package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib 18.*
    - opencv 2.4.*  # [not py3k]
    - cypico 0.2.*
    - cyffld2 0.2.*
    - menpo 0.6.*

test:

  requires:
    - nose
    - nose-exclude

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv  # [not py3k]
    - menpodetect.pico
    - menpodetect.ffld2

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
